apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  #owner: guests
  owner: group:default/admins

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform-core
spec:
  #owner: guests
  owner: group:default/admins