
auth:
  providers:
    gitlab:
      development:
        audience: https://gitlab.vertigo-devops.com
        authorizationUrl: https://gitlab.vertigo-devops.com/oauth/authorize
        tokenUrl: https://gitlab.vertigo-devops.com/oauth/token
        callbackUrl: http://localhost:7007/api/auth/gitlab/handler/frame

integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://${GITLAB_HOST}/api/v4
